version: '3.8'

services:
  inspector:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://inspector:password@db:5432/inspector
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=INFO
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - inspector-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=inspector
      - POSTGRES_USER=inspector
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - inspector-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - inspector
    restart: unless-stopped
    networks:
      - inspector-network

volumes:
  postgres_data:

networks:
  inspector-network:
    driver: bridge 